export const DEFAULT_PRICE_RANGE_MIN = 0 as const;
export const DEFAULT_PRICE_RANGE_MAX = 1000 as const;
export const DEFAULT_RATING = 0 as const;
export const DEFAULT_SORT = "name-asc" as const;
export const DEBOUNCED_SEARCH_DELAY = 500 as const;
export const DEFAULT_PRICE_STEP = 10 as const;
export const DEFAULT_RATING_STEP = 1 as const;
export const DEFAULT_RATING_MAX = 5 as const;
export const DEFAULT_PRICE_RANGE = [DEFAULT_PRICE_RANGE_MIN, DEFAULT_PRICE_RANGE_MAX] as const;
