import { createTransport, type Transporter } from "nodemailer";
import { Environment } from "../../constants/Environment";
import { IEmailService, NewReportEmailPayload, ReportResolutionEmailPayload } from "./IEmailService";

// TODO: Implement html templates
export class NodemailerService implements IEmailService {
  private transporter: Transporter;

  constructor() {
    this.transporter = createTransport({
      service: "Gmail",
      auth: {
        user: Environment.SMTP_USER,
        pass: Environment.SMTP_PASS,
      },
    })
  }

  async sendNewReportNotification(payload: NewReportEmailPayload): Promise<void> {
    await this.transporter.sendMail({
      from: `LocalFriend <${Environment.EMAIL_FROM}>`,
      to: Environment.TEST_EMAIL,
      subject: `New Report - ID ${payload.reportId}`,
      text: `Report generated by ${payload.reporterName} for ${payload.targetDescription}`,
    })
  }

  async sendReportResolutionNotification(payload: ReportResolutionEmailPayload): Promise<void> {
    await this.transporter.sendMail({
      from: `LocalFriend <${Environment.EMAIL_FROM}>`,
      to: Environment.TEST_EMAIL,
      subject: `Report Resolution - ID ${payload.reportId}`,
      text: `Report resolution for ${payload.reporterName}`,
    })
  }
}